#!/bin/bash

cd "$(dirname "$0")"

SERVERNAME="FREEBUILD"

source ../../../.secrets/discordsrv

cp -rv ../shared/configs/plugins .

sed -i "s/BotToken: \"\"/BotToken: \"${FREEBUILD_TOKEN}\"/" ./plugins/DiscordSRV/config.yml
sed -i "s/Channels: {\"global\": \"\"}/Channels: {\"global\": \"${FREEBUILD_TOKEN}\"}/" ./plugins/DiscordSRV/config.yml
sed -i "s/DiscordConsoleChannelId: \"\"/DiscordConsoleChannelId: \"${CONSOLE_CHANNEL}\"/" ./plugins/DiscordSRV/config.yml
sed -i "s/DiscordInviteLink: \"\"/DiscordInviteLink: \"${DISCORD_INVITE}\"/" ./plugins/DiscordSRV/config.yml

PAPER_JAR=$(ls -t paper-*.jar | head -n 1)

MEM_MIN="4G"
MEM_MAX="8G"

java -Xms$MEM_MIN -Xmx$MEM_MAX -jar $PAPER_JAR nogui --world-container worlds